[project]
name = "fastapi-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic-settings>=2.9.1",
    "tortoise-orm[asyncpg]>=0.25.0",
    "typer>=0.15.3",
]
