version: "3.8"
services:
  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  postgres_data:
    driver: local
